config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    get 'search', on: :collection
  end

  namespace :api do

    # API Devise routes
      post 'users', to: 'registrations#create'
      patch 'users', to: 'registrations#update'
      post 'users/sign_in', to: 'sessions#create'
      post 'users/password', to: 'passwords#create'

    resources :users

    resources :articles do
        resources :comments, only: [:create]
        put :reorder, on: :collection
    end

    resources :comments, only: [:update, :destroy] do
      put :reorder, on: :collection
    end
  end

  resources :articles do
    resources :comments
    get 'search', on: :collection
  end

  resources :admins do
    get 'search', on: :collection
  end

  resources :superadmins do
    get 'search', on: :collection
  end

  root 'welcome#index'
end

app/views/admins/_form.html.erb
<%= form_for @admin, url: action do |f| %>

<% if @admin.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @admin.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <h3>
    <%= f.label :avatar %>
  </h3>
  <p>
    <%= f.label :avatar %>
    <%= image_tag(@admin.avatar.thumb.url) if @admin.avatar? %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
    <%= f.label :remove_avatar do %>
      <%= f.check_box :remove_avatar %> Remove Avatar
    <% end %>
  </p>

  <h3>
    <%= f.label :first_name %>
  </h3>
  <p>
    <%= f.text_field :first_name %>
  </p>

  <h3>
    <%= f.label :last_name %>
  </h3>
  <p>
    <%= f.text_field :last_name %>
  </p>

  <h3>
    <%= f.label :email %>
  </h3>
  <p>
    <%= f.email_field :email %>
  </p>

  <h3>
    <%= f.label :password %>
  </h3>
  <p>
    <%= f.password_field :password %>
  </p>

  <h3 class="articles-form-headers">
      <%= f.label :biography %><br>
  </h3>
  <p>
    <%= f.text_area :biography, class: "summernote", placeholder: 'minimum: 2, maximum: 1,000,000' %>
  </p>

  <h3>
    <%= f.submit class: 'btn btn-default' %>
  </h3>
  <h3>
    <%= link_to 'Cancel', admins_path, class: 'btn btn-danger' %>
  </h3>

<% end %>

app/views/admins/_search.html.erb
<form action="<%= search_admins_path %>" method="get">
  <%= text_field_tag 'q', q, placeholder: 'Search By Admin Name' %>
  <div class="in-search">
    <%= submit_tag 'Find Admin', name: nil, class: 'btn btn-default' %>
  </div>
</form>

app/views/admins/edit.html.erb
<% if current_user.has_role? :superadmin or current_user.has_role? :god %>

  <div class="admins">
    <h1 class="page-header" align="center">Edit <%= @admin.name %></h1>

    <%= render partial: 'admins/form', locals: { action: admin_path(@admin) } %>
  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

<% end %>

app/views/admins/index.html.erb
<% if current_user.has_role? :superadmin or current_user.has_role? :god %>
  <div class="admins">
    <h1 class="page-header" align="center">Admins</h1>

    <%= render partial: 'admins/search', locals: { q: '' } %>

    <table>
      <tr>
        <th class="admins-index-table-headlines">Name</th>
        <th class="admins-index-table-headlines">Email</th>
        <% if can? :create, User %>
          <th colspan="2">
            <%= link_to 'New Administrator', new_admin_path, class: 'btn btn-success' %>
          </th>
        <% end %>
      </tr>
      <% @admins.each do |admin| %>
        <tr>
          <td align="left"><%= link_to image_tag(admin.avatar.small_thumb.url, class: 'side-pic'), admin  %> &nbsp; <%= link_to admin.name, admin_path(admin) %></td>
          <td><%= mail_to admin.email, admin.email %></td>
          <% if can? :manage, admin %>
            <td><%= link_to 'Edit', edit_admin_path(admin), class: 'btn btn-default' %></td>
            <td><%= link_to 'Delete', admin_path(admin) , class: 'btn btn-danger',
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </table>

  </div><!--. admins -->

<% else %>
  <h1 class="page-header" align="center">You are not authorized</h1>
<% end %>

app/views/admins/new.html.erb
<% if current_user.has_role? :superadmin or current_user.has_role? :god %>

  <div class="admins">
    <h1 class="page-header" align="center">New Admin</h1>

    <%= render partial: 'admins/form', locals: { action: admins_path } %>
  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

<% end %>

app/views/admins/search.html.erb
<% if current_user.has_role? :superadmin or current_user.has_role? :god %>

  <div class="admins">

    <br>
    <%= render partial: 'admins/search', locals: { q: @query } %>

    <table>
      <thead>
        <tr>
          <th><h1 class="page-header" align="center">Search results for:<br> "<%= @query %>"</h1></th>
        </tr>
      </thead>
      <tbody>
        <% @admins.each do |admin| %>
        <tr>
          <td><%= link_to image_tag(admin.avatar.small_thumb.url, class: 'side-pic'), admin_path(admin)  %> &nbsp; <%= link_to admin.name, admin_path(admin) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pagination"><%= will_paginate @admins %></div>

  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

<% end %>

app/views/admins/show.html.erb
<% if current_user.has_role? :superadmin or current_user.has_role? :god %>

  <div class="admins">

    <h1 class="page-header"><%= @admin.name %></h1>

    <h2 class="page-header"><%= mail_to @admin.email, @admin.email %></h2>

    <div class="ih-item circle effect11 top_to_bottom"><a href="#">
      <%= image_tag @admin.avatar.thumb.url, class: 'img' %>
      <div class="info">
        <div class="info-back">
          <h3><%= image_tag @admin.avatar.thumb.url, class: 'ih-item square effect15 top_to_bottom' %></h3>
        </div><!-- .info-back -->
      </div><!-- .info --></a>
    </div><!-- .ih-item circle effect18 top_to_bottom -->

    <div class="articles-show-lefty">
      <%= raw(@admin.biography) %>
    </div>

    <% if can? :update, @admin %>
      <p><%= link_to 'back', admins_path(@admins), class: 'btn btn-default' %> &nbsp; <%= link_to 'Edit', edit_admin_path(@admin), class: 'btn btn-default' %> &nbsp; <%= link_to 'Delete', admin_path(@admin) , class: 'btn btn-danger',
        method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

<% end %>