config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    get 'search', on: :collection
  end

  namespace :api do

    # API Devise routes
      post 'users', to: 'registrations#create'
      patch 'users', to: 'registrations#update'
      post 'users/sign_in', to: 'sessions#create'
      post 'users/password', to: 'passwords#create'

    resources :users

    resources :articles do
        resources :comments, only: [:create]
        put :reorder, on: :collection
    end

    resources :comments, only: [:update, :destroy] do
      put :reorder, on: :collection
    end
  end

  resources :articles do
    resources :comments
    get 'search', on: :collection
  end

  resources :admins do
    get 'search', on: :collection
  end

  resources :superadmins do
    get 'search', on: :collection
  end

  root 'welcome#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy

  belongs_to :user

  validates :title, presence: true,
                    length: { minimum: 1, maximum: 25 }
  validates :text, presence: true,
                    length: { minimum: 1, maximum: 1000000000 }

  mount_uploader :poster, PosterUploader

end

app/controllers/api/articles_controller.rb
class Api::ArticlesController < Api::ApplicationController

  before_filter :authenticate_user_from_token!
  before_filter :authenticate_user!
  load_and_authorize_resource

  before_action :set_article, only: [:show, :update, :destroy]

  # GET /articles
  def index
    @articles = Article.unscoped.order(:title)
    render json: @articles
  end

  # GET /articles/1
  def show
    json = @article.as_json
    if params[:expand].present? && params[:expand].split(',').include?('comments')
      json = @article.as_json(include: [:comments])
    end
    render json: json
  end

  # POST /articles
  def create
    @article = Article.new(article_params)
      if @article.save
        render json: @article, status: :created
      else
        render json: @article.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update_attributes(article_params)
      head :no_content
    else
      render json: @article.errors, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    head :no_content
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.unscoped.find(params[:id])
    render json: @article.as_json(include: [:comments])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.permit(:title, :text)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :article

  helper_method :sort_column, :sort_direction

  def index
    @articles = Article.order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params) # Assign first
    @article.user = current_user # Then access attributes/associations

    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  # GET /articles/search?q=
  def search
    @query = params[:q]
    @articles = []
    if @query.present?
      @articles = Article.where("lower(title) LIKE ?", "%#{@query.downcase}%").paginate(:page => params[:page], :per_page => 10)
    else
      @articles = Article.order(:title).paginate(:page => params[:page], :per_page => 10)
    end
  end

  private

  def sort_column
    Article.column_names.include?(params[:sort]) ? params[:sort] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def article_params
      params.require(:article).permit(:title, :text, :poster, :poster_cache, :remove_poster)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3>
    <%= f.label :poster %>
  </h3>
  <p>
    <%= f.label :poster %>
    <%= image_tag(@article.poster.thumb.url) if @article.poster? %>
    <%= f.file_field :poster %>
    <%= f.hidden_field :poster_cache %>
    <%= f.label :remove_poster do %>
      <%= f.check_box :remove_poster %> Remove Poster
    <% end %>
  </p>

  <h3 class="articles-form-headers">
      <%= f.label :title %><br>
  </h3>
    <p>
      <%= f.text_field :title, placeholder: 'maximum: 25 characters' %>
    </p>

  <h3 class="articles-form-headers">
      <%= f.label :text %><br>
  </h3>
    <p>
      <%= f.text_area :text, class: "summernote", placeholder: 'maximum: 1,000,000 characters' %>
    </p>

    <h3>
      <%= f.submit class: 'btn btn-default' %>
    </h3>

    <h3>
      <%= link_to 'Cancel', articles_path, class: 'btn btn-danger' %>
    </h3>

<% end %>

app/views/articles/_search.html.erb
<form action="<%= search_articles_path %>" method="get">
  <%= text_field_tag 'q', q, placeholder: 'Search By Article Title' %>
  <div class="in-search">
    <%= submit_tag 'Find Article', title: nil, class: 'btn btn-default' %>
  </div>
</form>

app/views/articles/edit.html.erb
<div class="articles">
  <h1 class="page-header" align="center">Edit <%= @article.title %></h1>
  <h2>Created <%= @article.created_at.strftime("%B %-d, %Y") %></h2>
  <h2 class="articles-show-updated-sub-header">Updated <%= @article.updated_at.strftime("%B %-d, %Y") if @article.updated_at.present? %></h2>

  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="articles">

  <h1 class="page-header" align="center">Articles</h1>

  <%= render partial: 'articles/search', locals: { q: '' } %>

  <% if @articles.present? %>

    <table>
      <tr>
        <th class="articles-index-table-headlines">Author</th>
        <th class="articles-index-table-headlines"><%= sortable "title", "Title" %></th>
        <!-- <th class="articles-index-table-headlines">Text</th> -->
        <th colspan="2">
          <% if can? :create, Article %>
            <%= link_to 'Create a New Article', new_article_path, class: 'btn btn-success' %>
          <% end %>
        </th>
      </tr>
      <% @articles.each do |article| %>
        <tr>
          <td align="left"><%= link_to image_tag(article.user.avatar.small_thumb.url, class: 'side-pic'), article.user  %> &nbsp; <%= link_to article.user.name, article.user %></td>
          <td><%= link_to article.title, article_path(article) %></td>
          <!-- <td><%= article.text %></td> -->
          <% if current_user.has_role? :god or current_user == article.user %>
            <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-default' %></td>
            <td><%= link_to 'Delete', article_path(article) , class: 'btn btn-danger',
                            method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% else %>
            <td></td>
            <td>
              <div class="ih-item circle effect20 top_to_bottom">
                <a href="#">
                  <%= image_tag article.poster.thumb.url, class: 'img' %>
                  <div class="info">
                    <div class="info-back">
                      <h3><%= image_tag article.poster.thumb.url, class: 'ih-item square' %></h3>
                    </div><!-- .info-back -->
                  </div><!-- .info -->
                </a>
              </div><!-- .ih-item circle effect18 top_to_bottom -->
            </td>
          <% end %>
        </tr>
      <% end %>
    </table>

    <div class="pagination"><%= will_paginate @articles %></div>

  <% else %>


    <h1><%= image_tag 'simpsons.png', class:"articles-index-nothing-yet-pic-1" %> <%= image_tag 'simpsons.png', class:"articles-index-nothing-yet-pic-2" %></h1>

    <% if can? :create, Article %>
      <h1 class="spinner">
        <%= link_to 'Create a New Article', new_article_path, class: 'btn btn-success' %>
      </h1><!--. spinner -->
    <% end %>


  <% end %>

</div><!--. articles -->

app/views/articles/new.html.erb
<div class="articles">
  <% if can? :create, Article %>
    <h1 class="page-header" align="center">New Article</h1>
    <%= render 'form' %>
  <% else %>
    <h1 class="page-header" align="center">You are not authorized</h1>
  <% end %>
</div><!--. articles -->

app/views/articles/search.html.erb
<div class="articles">

  <br>
  <%= render partial: 'articles/search', locals: { q: @query } %>

  <table>
    <thead>
      <tr>
        <th><h1 class="page-header" align="center">Search results for:<br> "<%= @query %>"</h1></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= link_to image_tag(article.poster.small_thumb.url, class: 'side-pic'), article_path(article)  %> &nbsp; <%= link_to article.title, article_path(article) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="pagination"><%= will_paginate @articles %></div>

</div><!--. articles -->

app/views/articles/show.html.erb
<div class="articles">
  <h1 class="page-header" align="center">"<%= @article.title %>"<br><%= link_to image_tag(@article.user.avatar.small_thumb.url, class: 'side-pic'), @article.user  %> &nbsp; <%= link_to @article.user.name, @article.user %></h1>
  <h2 class="articles-show-updated-sub-header">Created <%= @article.created_at.strftime('%b %-d, %Y, %l:%M %p, %Z') %><br>Updated <%= @article.updated_at.strftime('%b %-d, %Y, %l:%M %p, %Z') if @article.updated_at.present? %></h2>

  <div class="ih-item circle effect20 top_to_bottom"><a href="#">
    <a href="#">
      <%= image_tag @article.poster.thumb.url, class: 'img' %>
      <div class="info">
        <div class="info-back">
          <h3><%= image_tag @article.poster.thumb.url, class: 'ih-item square' %></h3>
        </div><!-- .info-back -->
      </div><!-- .info -->
    </a>
  </div><!-- .ih-item circle effect18 top_to_bottom -->

  <div class="articles-show-lefty">
    <h1></h1>
    <%= raw(@article.text) %>
  </div>

  <table>
    <tr>
      <% if current_user.has_role? :god or current_user == @article.user %>
        <td><%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-default' %></td>
        <td><%= link_to 'Delete', article_path(@article) , class: 'btn btn-danger',
                                method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  </table>

  <!-- <h2 class="comments">Comments</h2> -->
  <%= render @article.comments if @article.comments.present? %>
  <% if can? :manage, Comment %>
    <h3 class="comment">Add a comment:</h3>
    <%= render "comments/form" %>
  <% end %>

</div><!--. articles -->