config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    get 'search', on: :collection
  end

  namespace :api do

    # API Devise routes
      post 'users', to: 'registrations#create'
      patch 'users', to: 'registrations#update'
      post 'users/sign_in', to: 'sessions#create'
      post 'users/password', to: 'passwords#create'

    resources :users

    resources :articles do
        resources :comments, only: [:create]
        put :reorder, on: :collection
    end

    resources :comments, only: [:update, :destroy] do
      put :reorder, on: :collection
    end
  end

  resources :articles do
    resources :comments
    get 'search', on: :collection
  end

  resources :admins do
    get 'search', on: :collection
  end

  resources :superadmins do
    get 'search', on: :collection
  end

  root 'welcome#index'
end

app/controllers/superadmins_controller.rb
class SuperadminsController < ApplicationController
  before_action :cancan_rails4_hack
  load_and_authorize_resource :superadmin, class: User.with_role(:superadmin)

  def cancan_rails4_hack
    @superadmin = User.new
  end

  def index
    @superadmin = User.with_role(:superadmin).all
  end

  def show
    @superadmin = User.find(params[:id])
  end

  def new
    @superadmin = User.new
    @superadmin.add_role :superadmin
  end

  def edit
    @superadmin = User.find(params[:id])
  end

  def create
    @superadmin = User.new(superadmin_params)
    # @admin.password = Devise.friendly_token.first(8)

    respond_to do |format|
      if @superadmin.save
        @superadmin.add_role :superadmin
        format.html { redirect_to superadmin_path(@superadmin), notice: 'Super was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @superadmin = User.find(params[:id])

    if params[:user][:password].empty?
      logger.debug 'should delete password here'
      params[:user].delete :password
    end

    logger.debug "params = #{params}"

    respond_to do |format|
      if @superadmin.update_attributes(superadmin_params)
        format.html { redirect_to superadmin_path(@superadmin), notice: 'Super was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @superadmin = User.find(params[:id])
    @superadmin.destroy

    respond_to do |format|
      format.html { redirect_to superadmins_path, notice: 'Super was successfully deleted.' }
    end
  end

  # GET /superadmins/search?q=
  def search
    @query = params[:q]
    @superadmins = []
    if @query.present?
      @superadmins =  User.with_role(:superadmin).where("lower(first_name) LIKE ? OR lower(last_name) LIKE ?", "%#{@query.downcase}%", "%#{@query.downcase}%").paginate(:page => params[:page], :per_page => 10)
    else
      @superadmins = User.with_role(:superadmin).order('users.last_name, users.first_name').paginate(:page => params[:page], :per_page => 10)
    end
  end

  private

  def superadmin_params
    params.require(:user).permit(:email, :first_name, :last_name, :password, :biography, :avatar, :avatar_cache, :remove_avatar)
  end

end

app/helpers/superadmins_helper.rb
module SuperadminsHelper
end

app/views/superadmins/_form.html.erb
<%= form_for @superadmin, url: action do |f| %>

<% if @superadmin.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% @superadmin.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<h3>
  <%= f.label :avatar %>
</h3>
<p>
  <%= f.label :avatar %>
  <%= image_tag(@superadmin.avatar.thumb.url) if @superadmin.avatar? %>
  <%= f.file_field :avatar %>
  <%= f.hidden_field :avatar_cache %>
  <%= f.label :remove_avatar do %>
    <%= f.check_box :remove_avatar %> Remove Avatar
  <% end %>
</p>

<h3>
  <%= f.label :first_name %>
</h3>
<p>
  <%= f.text_field :first_name %>
</p>

<h3>
  <%= f.label :last_name %>
</h3>
<p>
  <%= f.text_field :last_name %>
</p>

<h3>
  <%= f.label :email %>
</h3>
<p>
  <%= f.email_field :email %>
</p>

<h3>
  <%= f.label :password %>
</h3>
<p>
  <%= f.password_field :password %>
</p>

<h3 class="articles-form-headers">
    <%= f.label :biography %><br>
</h3>
<p>
  <%= f.text_area :biography, class: "summernote", placeholder: 'minimum: 2, maximum: 1,000,000' %>
</p>

<h3>
  <%= f.submit class: 'btn btn-default' %>
</h3>
<h3>
  <%= link_to 'Cancel', superadmins_path, class: 'btn btn-danger' %>
</h3>

<% end %>

app/views/superadmins/_search.html.erb
<form action="<%= search_superadmins_path %>" method="get">
  <%= text_field_tag 'q', q, placeholder: 'Search By Super Admin Name' %>
  <div class="in-search">
    <%= submit_tag 'Find Super Admin', name: nil, class: 'btn btn-default' %>
  </div>
</form>

app/views/superadmins/edit.html.erb
<% if current_user.has_role? :god %>

  <div class="admins">
    <h1 class="page-header">Edit <%= @superadmin.name %></h1>

    <%= render partial: 'superadmins/form', locals: { action: superadmin_path(@superadmin) } %>
  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

  <p align="center">Only the system admin can view and edit super admins.</p>

<% end %>

app/views/superadmins/index.html.erb
<% if current_user.has_role? :god %>

  <div class="admins">
    <h1 class="page-header" align="center">Super Admins</h1>

    <%= render partial: 'superadmins/search', locals: { q: '' } %>

    <table>
      <tr>
        <th class="admins-index-table-headlines">Name</th>
        <th class="admins-index-table-headlines">Email</th>
        <% if can? :create, User %>
          <th colspan="2">
            <%= link_to 'New Super Admin', new_superadmin_path, class: 'btn btn-success' %>
          </th>
        <% end %>
      </tr>
      <% @superadmins.each do |superadmin| %>
      <tr>
        <td align="left"><%= link_to image_tag(superadmin.avatar.small_thumb.url, class: 'side-pic'), superadmin  %> &nbsp; <%= link_to superadmin.name, superadmin_path(superadmin) %></td>
        <td><%= mail_to superadmin.email, superadmin.email %></td>
        <% if can? :manage, superadmin %>
          <td><%= link_to 'Edit', edit_superadmin_path(superadmin), class: 'btn btn-default' %></td>
          <td><%= link_to 'Delete', superadmin_path(superadmin) , class: 'btn btn-danger',
          method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% end %>
    </table>

  </div><!--. admins -->

<% else %>


  <h1 class="page-header" align="center">You are not authorized</h1>

  <p align="center">Only the system admin can view and edit super admins.</p>


<% end %>

app/views/superadmins/new.html.erb
<% if current_user.has_role? :god %>

  <div class="admins">
    <h1 class="page-header">New Super Admin</h1>

    <%= render partial: 'superadmins/form', locals: { action: superadmins_path } %>
  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

  <p align="center">Only the system admin can view and edit super admins.</p>

<% end %>

app/views/superadmins/search.html.erb
<% if current_user.has_role? :god %>

  <div class="admins">

    <br>
    <%= render partial: 'superadmins/search', locals: { q: @query } %>

    <table>
      <thead>
        <tr>
          <th><h1 class="page-header" align="center">Search results for:<br> "<%= @query %>"</h1></th>
        </tr>
      </thead>
      <tbody>
        <% @superadmins.each do |superadmin| %>
        <tr>
          <td><%= link_to image_tag(superadmin.avatar.small_thumb.url, class: 'side-pic'), superadmin_path(superadmin)  %> &nbsp; <%= link_to superadmin.name, superadmin_path(superadmin) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="pagination"><%= will_paginate @superadmins %></div>

  </div><!--. admins -->

<% else %>

  <h1 class="page-header" align="center">You are not authorized</h1>

  <p align="center">Only the system admin can view and edit super admins.</p>

<% end %>

app/views/superadmins/show.html.erb
<% if current_user.has_role? :god %>


  <div class="admins">

    <h1 class="page-header"><%= @superadmin.name %></h1>

    <h2 class="page-header"><%= mail_to @superadmin.email, @superadmin.email %></h2>

    <div class="ih-item circle effect11 top_to_bottom"><a href="#">
      <%= image_tag @superadmin.avatar.thumb.url, class: 'img' %>
      <div class="info">
        <div class="info-back">
          <h3><%= image_tag @superadmin.avatar.thumb.url, class: 'ih-item square effect15 top_to_bottom' %></h3>
        </div><!-- .info-back -->
      </div><!-- .info --></a>
    </div><!-- .ih-item circle effect18 top_to_bottom -->

    <div class="articles-show-lefty">
      <%= raw(@superadmin.biography) %>
    </div>

    <% if can? :update, @superadmin %>
    <p><%= link_to 'back', superadmins_path(@superadmins), class: 'btn btn-default' %> &nbsp; <%= link_to 'Edit', edit_superadmin_path(@superadmin), class: 'btn btn-default' %> &nbsp; <%= link_to 'Delete', superadmin_path(@superadmin) , class: 'btn btn-danger',
      method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
  </div><!--. admins -->

  <h2 class="page-header" align="left">Articles</h2>
  <table>
    <% @superadmin.articles.each do |article| %>
      <tr>
        <td><%= link_to image_tag(article.poster.small_thumb.url, class: 'side-pic'), article_path(article)  %> &nbsp; <%= link_to article.title, article_path(article) %></td>
          <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-default' %></td>
          <td><%= link_to 'Delete', article_path(article) , class: 'btn btn-danger',
                          method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>


<% else %>


  <h1 class="page-header" align="center">You are not authorized</h1>

  <p align="center">Only the system admin can view and edit super admins.</p>


<% end %>