config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    get 'search', on: :collection
  end

  namespace :api do

    # API Devise routes
      post 'users', to: 'registrations#create'
      patch 'users', to: 'registrations#update'
      post 'users/sign_in', to: 'sessions#create'
      post 'users/password', to: 'passwords#create'

    resources :users

    resources :articles do
        resources :comments, only: [:create]
        put :reorder, on: :collection
    end

    resources :comments, only: [:update, :destroy] do
      put :reorder, on: :collection
    end
  end

  resources :articles do
    resources :comments
    get 'search', on: :collection
  end

  resources :admins do
    get 'search', on: :collection
  end

  resources :superadmins do
    get 'search', on: :collection
  end

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.has_role? :superadmin or current_user.has_role? :god
      @articles = Article.order(:title).paginate(:page => params[:page], :per_page => 10)
      @superadmins = User.with_role(:superadmin).order('users.last_name, users.first_name').paginate(:page => params[:page], :per_page => 10)
      @admins = User.with_role(:admin).order('users.last_name, users.first_name').paginate(:page => params[:page], :per_page => 10)
      @users = User.order(:last_name).paginate(:page => params[:page], :per_page => 30)
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<% if current_user.has_role? :god %>

  <h1 class="page-header" align="center">Rails Blog</h1>

  <h2 class="page-header">Super Admins</h2>
  <div class="admins">
    <%= render partial: 'superadmins/search', locals: { q: '' } %>
  </div>
  <table>
    <tr>
      <th class="admins-index-table-headlines">Name</th>
      <th class="admins-index-table-headlines">Email</th>
      <th colspan="2">
        <%= link_to 'New Super Admins', new_superadmin_path, class: 'btn btn-success' %>
      </th>
    </tr>
    <% @superadmins.each do |superadmin| %>
      <tr>
        <td align="left"><%= link_to superadmin.name, superadmin_path(superadmin) %></td>
        <td><%= mail_to superadmin.email, superadmin.email %></td>
        <td><%= link_to 'Edit', edit_superadmin_path(superadmin), class: 'btn btn-default' %></td>
        <td><%= link_to 'Delete', superadmin_path(superadmin) , class: 'btn btn-danger',
        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <h2 class="page-header">Admins</h2>
  <div class="admins">
    <%= render partial: 'admins/search', locals: { q: '' } %>
  </div>
  <table>
    <tr>
      <th class="admins-index-table-headlines">Name</th>
      <th class="admins-index-table-headlines">Email</th>
      <th colspan="2"></th>
    </tr>
    <% @admins.each do |admin| %>
      <tr>
        <td align="left"><%= link_to admin.name, admin_path(admin) %></td>
        <td><%= mail_to admin.email, admin.email %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin), class: 'btn btn-default' %></td>
        <td><%= link_to 'Delete', admin_path(admin) , class: 'btn btn-danger',
        method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>

  <h2 class="page-header">Users</h2>
  <div class="admins">
    <%= render partial: 'users/search', locals: { q: '' } %>
  </div>
  <table>
    <tr>
      <th class="admins-index-table-headlines">Name</th>
      <th class="admins-index-table-headlines">Email</th>
      <th colspan="2"></th>
    </tr>
    <% @users.each do |user| %>
    <tr>
      <% if user.has_role? :admin or user.has_role? :superadmin or user.has_role? :god %>
      <% else %>
        <td align="left"><%= link_to user.name, user_path(user) %></td>
        <td><%= mail_to user.email, user.email %></td>
        <td><%= link_to 'Edit', edit_user_registration_path, class: 'btn btn-default' %></td>
        <td><%= link_to 'Delete', user_path(user) , class: 'btn btn-danger',
                method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </table>

  <div class="pagination"><%= will_paginate @users %></div>


<% elsif current_user.has_role? :superadmin or current_user.has_role? :admin %>


  <h1 class="page-header" align="center">Rails Blog</h1>

  <h2 class="page-header" align="left">Bubbles</h2>
  <div class="bubbles">
    <ul class="bubbles-list">
      <li><a href= "https://github.com/CMBmaseda" target="_blank"><%= image_tag 'simpsons.png', class:'welcome-pic-1' %></a></li>
      <li><a href= "https://github.com/CMBmaseda" target="_blank"><%= image_tag 'simpsons.png', class:'welcome-pic-1' %></a></li>
      <li><a href= "https://github.com/CMBmaseda" target="_blank"><%= image_tag 'simpsons.png', class:'welcome-pic-1' %></a></li>
      <li><a href= "https://github.com/CMBmaseda" target="_blank"><%= image_tag 'simpsons.png', class:'welcome-pic-1' %></a></li>
      <li><a href= "https://github.com/CMBmaseda" target="_blank"><%= image_tag 'simpsons.png', class:'welcome-pic-1' %></a></li>
      <li><a href= "https://github.com/CMBmaseda" target="_blank"><%= image_tag 'simpsons.png', class:'welcome-pic-1' %></a></li>
    </ul><!--. bubbles-list -->
  </div><!--. bubbles -->


<% else %>


  <h1 class="page-header" align="center">Rails Blog</h1>

  <div class="articles">
    <%= render partial: 'articles/search', locals: { q: '' } %>
  </div>

  <%= link_to (image_tag 'simpsons.png', class:'welcome-pic-1'), controller: 'articles' %>

  <p>
    Scientific pitch notation is a logarithmic frequency scale. The octave number increases by 1 upon an ascension from B to C (and not from G to A, as one might expect). Thus "A4" refers to the first A above C4 (middle C). As another example, in ascending the white keys on a keyboard, C4 immediately follows B3, as in the following sequence: "C3 D3 E3 F3 G3 A3 B3 C4 D4". Scientific pitch notation is often used to specify the range of an instrument. It provides an unambiguous means of identifying a note in terms of musical notation rather than frequency, while at the same time avoiding the transposition conventions that are used in writing the music for instruments such as the clarinet and guitar. The conventional octave naming system — where for example C0 is written as ′′C, or C, or CCC in Helmholtz pitch notation, or referred to as subcontra C, and where C4 is written as c′ or one-lined C — applies to the written notes that may or may not be transposed. For example, a d′ played on a B♭ trumpet is actually a C4 in scientific pitch notation. Although pitch notation is intended to describe audible sounds, it can also be used to specify the frequency of non-audible phenomena. <a href="http://www.couriernewjersey.com/asbury-game-html5/asbury.html" target="_blank">HTML5 Game</a>
  </p>

  <iframe title="YouTube video player" class="welcome-vid-1" src="https://www.youtube.com/embed/JHu46QznBI4?rel=0" frameborder="0" allowfullscreen></iframe>

  <h2 class="page-header" align="left">iHover</h2>

  <div class="row" align="center">
    <div class="col-sm-6">
      <div class="ih-item square effect12 top_to_bottom">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="ih-item square colored effect12 top_to_bottom">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
  </div><!-- End Row -->
  <div class="row" align="center">
    <div class="col-sm-6">
      <div class="ih-item square effect12 bottom_to_top">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="ih-item square colored effect12 bottom_to_top">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
  </div><!-- End Row -->
  <div class="row" align="center">
    <div class="col-sm-6">
      <div class="ih-item circle effect18 left_to_right">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="ih-item circle colored effect18 right_to_left">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
  </div><!-- End Row -->
  <div class="row" align="center">
    <div class="col-sm-6">
      <div class="ih-item circle effect18 left_to_right">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="ih-item circle effect18 right_to_left">
        <a href="#">
          <%= image_tag 'simpsons.png', class:"img" %>
          <div class="info">
            <h3><%= current_user.name %></h3>
            <p>Link has to be 'href'</p>
          </div>
        </a>
      </div>
    </div>
  </div><!-- End Row -->

<% end %>